### ISSUE TITLE
Nondeterministic lemmatization behavior

### ISSUE THREAD

**Issue by f11r** [Liebeck/IWNLP-py#2]
Really appreciate your work.

At the moment the lemmatization seems to be nondeterministic. For example running
~~~
from iwnlp.iwnlp_wrapper import IWNLPWrapper
lemmatizer = IWNLPWrapper(lemmatizer_path='IWNLP.Lemmatizer_20170501.json')
print(lemmatizer.lemmatize_plain('ein', False))
~~~
sometimes gives `['einen', 'ein']` and sometimes `['ein', 'einen']`.

Is there already a way to get deterministic results? If not I see two possible solutions:

1. If some kind of confidence values are available for each lemma option, return the list sorted by confidence.
2. Return a set of lemmas instead of a list and let the user figure out which lemma to choose.

**Comment by Liebeck** [comment]
Hi, thanks for your feedback!
I wasn't aware that the lookup is nondeterministic. I will debug this and definetly fix it.  
Unfortunately, I don't have access to confidence values. 

> Return a set of lemmas instead of a list and let the user figure out which lemma to choose.

This is what I intended with the list since word sense disambiguation is sometimes required, for instance Kohle -> Kohl, Kohle

I plan to adress the issue on Tuesday and release a new version for pip.

**Comment by Liebeck** [comment]
The returned lemmas are now sorted to have deterministic sort order. I uploaded a new version for pip. I hope this fixes your issue?

**Comment by f11r** [comment]
It does. Thanks for the quick reply.
