### ISSUE TITLE
Default lemmatizer included

### ISSUE THREAD

**Issue by kasteph** [Liebeck/IWNLP-py#3]
Hi @Liebeck,

first of all, thanks for this awesome package! Is there any particular reason why an IWNLP dump is not included by default in the pip package (is it due to size?)? It would be nice to have while giving the user the option to specify their own path.

Cheers,
Steph

**Comment by Liebeck** [comment]
Hi @stephsamson thanks for your kind feedback. The processed dump is not included since it is CC-licensed while IWNLP-py is MIT-licensed. I'm not sure if I can mix both of them.

What do you mean by giving the user the option to specify their own path. The IWNLPWrapper class has a parameter called `lemmatizer_path` which should do exactly that. Did you have something different in mind?

**Comment by kasteph** [comment]
Ahh gotcha, that makes sense. I just meant that it would be nice to have both a path specifying to the package .json dump and the `lemmatizer_path` that is currently in place. Sorry, I should have written that much clearer!
